ENG-6030 CFT Many many fixes for VPC deployment
- Actually works with non-public ips now
- NVME boot wait reduced by a lot
- Uses much tighter security boundary
- Much simpler template, many permissions removed.
- Using EFS Access Points which are far better
  suited for us here (and on SaaS). There's a limit
  of 1 EFS Mount Target per Subnet, but EFSAP has
  no such problems.
- Control over the mount point (KPMG has this problem)
- Many new (optional) arguments, like SSH Key,
  existing EFS or any other NFS server will work (4.x)
- You can deploy into a a Vpc and share existing
  security groups, routes, vpc endpoints, etc.
- AdminPassword is stored securely now, not leakead
  in logs
- Circular dependencies in Security Groups fixed
- Reworked bootup a lot
- Added tests
- Dynamic resize working again

Change-Id: I551c7a215d9f5079f922adbcde0d8650a5abcbb9

diff --git a/bin/dc2 b/bin/dc2
--- a/bin/dc2
+++ b/bin/dc2
@@ -82,6 +82,7 @@ s3_cmd() {
             quiet=''
             set -x
         fi
+        local content
         aws s3 $cmd $quiet \
             --acl public-read \
             --metadata-directive REPLACE \
@@ -110,10 +111,8 @@ ec2_image_tags() {
 }
 
 xcalar_latest() {
-    AMZN1HVM_US_EAST_1=$(ec2_find_ami --filters "Name=tag:Version,Values=${VERSION}" 'Name=name,Values=xdp-*' --owner self --region us-east-1)
-    AMZN1HVM_US_WEST_2=$(ec2_find_ami --filters "Name=tag:Version,Values=${VERSION}" 'Name=name,Values=xdp-*' --owner self --region us-west-2)
-    echo "ami_us_east_1: $AMZN1HVM_US_EAST_1" > $TEMPLATEDIR/vars/amis.yaml
-    echo "ami_us_west_2: $AMZN1HVM_US_WEST_2" >> $TEMPLATEDIR/vars/amis.yaml
+    AMZN1HVM_US_EAST_1=$(ec2_find_ami --filters "Name=tag:Version,Values=${VERSION}" 'Name=name,Values='${PROJECT}'*' --owner self --region us-east-1)
+    AMZN1HVM_US_WEST_2=$(ec2_find_ami --filters "Name=tag:Version,Values=${VERSION}" 'Name=name,Values='${PROJECT}'*' --owner self --region us-west-2)
     case "$AWS_DEFAULT_REGION" in
         us-west-2)
             IMAGE_ID=$AMZN1HVM_US_WEST_2
@@ -176,7 +175,7 @@ j2transform() {
 dc2_parse_common() {
     local cmd="$1" key='' val=''
     shift
-    valid_parse_common_keys=(debug publishing product project release cloud osid image_id
+    valid_parse_common_keys=(debug publishing product project release cloud osid image_id prefix
 	installer installer_url installer_version installer_build_number installer_build_type installer_rc installer_xce_branch installer_xce_sha1
     installer_xd_branch installer_xd_sha1 image_build_number installer_byjob docker_image release product license license_type installer_tag)
     case "$cmd" in
@@ -196,9 +195,14 @@ dc2_parse_common() {
             DEBUG=1
             KEEP=1
             ;;
-        --publishing) PUBLISHING=True ;;
+        --publishing) PUBLISHING=true ;;
         --product)
             PRODUCT="$1"
+            echo 2
+            ;;
+        --prefix)
+            PREFIX="${1#/}"
+            PREFIX="${PREFIX%/}/"
             echo 2
             ;;
         --project | -p)
@@ -259,7 +263,7 @@ dc2_parse_common() {
             echo 2
             ;;
         --environment | --env | -e)
-            ENVIRONMENT="$1"
+            declare -g -r ENVIRONMENT="$1"
             echo 2
             ;;
         --template)
@@ -378,9 +382,21 @@ dc2_deploy() {
 
 }
 
+dc2conf() {
+    if ! test -e "$PROJDIR"/.dc2.yml; then
+        return 1
+    fi
+    PROJDC2="${PROJDC2:-$TMPDIR/dc2.json}"
+    if ! test -e "$PROJDC2"; then
+        cfn-flip < "$PROJDIR"/.dc2.yml > "$PROJDC2"
+    fi
+
+    jq -r "$1" < "$PROJDC2"
+}
+
 dc2_upload() {
     local cmd shift_amount
-    FLAVORS="default"
+    FLAVORS="${FLAVORS:-default}"
     USER_VARS_FILES=()
     while [[ $# -gt 0 ]]; do
         cmd="$1"
@@ -398,6 +414,10 @@ dc2_upload() {
             --find-ami) FIND_AMI=1 ;;
             --flavors)
                 FLAVORS="$1"
+                shift
+                ;;
+            --inline-script)
+                INLINE_SCRIPT="$1"
                 shift
                 ;;
             -D)
@@ -427,6 +447,10 @@ dc2_upload() {
         VERSION="$INSTALLER_VERSION"
     fi
 
+    if [ -z "$ENVIRONMENT" ]; then
+        declare -r -g ENVIRONMENT=dev
+    fi
+    declare -g -r ENVYAML="${TEMPLATEDIR}/env/${ENVIRONMENT}.yaml"
 
     J2DEFS+=(-D "DEBUG=${DEBUG}")
     J2DEFS+=(-D "PUBLISHING=${PUBLISHING^}")
@@ -434,27 +458,10 @@ dc2_upload() {
     test -n "${PROJECT:-}" || die "Need to set --project"
     test -n "${VERSION:-}" || VERSION=$(cat $PROJECT/VERSION) || die "Need to set --version"
     PROJDIR="${TEMPLATEDIR}/${PROJECT}"
-    CONTEXT="${ENVIRONMENT}/${PROJECT}/${TAG}"
+    CONTEXT="${ENVIRONMENT}/${PROJECT}/${TAG}${RELEASE}"
     test -e "$PROJDIR" || die "$PROJDIR doesn't exist. You need to set $XLRINFRADIR/${CLOUD}/cfn as your working directory"
-
-    GENDIR="$TMPDIR"/gen
-    mkdir -p "$GENDIR"/scripts/
-    for ii in "$PROJDIR"/scripts/*; do
-        if [[ $ii =~ .j2$ ]]; then
-            cat "$PROJDIR"/vars/*.yaml "${USER_VARS_FILES[@]}" | jinja2 "${J2DEFS[@]}" "$ii" > $GENDIR/scripts/$(basename $ii .j2)
-        else
-            cp $ii $GENDIR/scripts/
-        fi
-    done
-    if test -e "$PROJDIR"/lambda; then
-        mkdir -p "$GENDIR"/lambda
-        cp "$PROJDIR"/lambda/*.py "$GENDIR"/lambda/
-        if test -e "$PROJDIR"/lambda/requirements.txt; then
-            pip install -q -r "$PROJDIR"/lambda/requirements.txt -c "$PROJDIR"/lambda/constraints.txt -t "$GENDIR"/lambda
-        fi
-        (cd "$GENDIR"/lambda && zip -q -9r "$GENDIR"/lambda.zip .)
-        rm -rf "$GENDIR"/lambda
-    fi
+    declare -g -r GENDIR="$TMPDIR"/gen
+    mkdir -p "$GENDIR"
 
     case "$AWS_DEFAULT_REGION" in
         us-west-2) BUCKET=xcrepo ;;
@@ -466,7 +473,13 @@ dc2_upload() {
     esac
 
     BUCKET_ENDPOINT="$(aws_s3_url s3://$BUCKET)"
-    TARGET=cfn/${CONTEXT}
+    NOW=$(date +%s)
+    if [ "$IS_AUTOMATED" = true ]; then
+        PREFIX="${PREFIX}cfn/"
+    else
+        PREFIX="${PREFIX}cfn-user/"
+    fi
+    TARGET=${PREFIX}${CONTEXT}
     BASE_URL="${BUCKET_ENDPOINT}/${TARGET}"
     bootstrapUrl="${BASE_URL}/scripts/user-data.sh"
     bucketLocation=$(aws s3api get-bucket-location --bucket $BUCKET --query LocationConstraint --output text)
@@ -477,10 +490,10 @@ dc2_upload() {
     rm -fv "$TMPDIR"/vars/* "$TMPDIR"/allvars.*
 
     cat > "$TMPDIR"/vars/deploy.yaml <<- EOF
+	ENVIRONMENT: ${ENVIRONMENT}
 	VERSION: '$VERSION'
 	PROJECT: '$PROJECT'
 	${RELEASE:+RELEASE: "'$RELEASE'"}
-	ENVIRONMENT: $ENVIRONMENT
 	TAG: '$TAG'
 	installer_tag: '$INSTALLER_TAG'
 	installer_version: '$INSTALLER_VERSION'
@@ -492,21 +505,21 @@ dc2_upload() {
 	basePrefix: '${TARGET}/'
 	baseLocation: '${bucketLocation}'
 	baseUrlPath: 'https://s3.${bucketLocation}.amazonaws.com/${BUCKET}/${TARGET}/'
-	baseUrlVirtual: 'https://${BUCKET}.s3.amazonaws.com/${TARGET}/'
+	baseUrlVirtual: 'https://${BUCKET}.s3-${bucketLocation}.amazonaws.com/${TARGET}/'
 	Bucket: '$BUCKET'
 	Prefix: '$TARGET'
 	bootstrapUrl: '$bootstrapUrl'
-	${PUBLISHING:+PUBLISHING: "${PUBLISHING^}"}
-	${DEBUG:+DEBUG: $DEBUG}
-	Date: '$(date +%FT%T%z)'
+	PUBLISHING: ${PUBLISHING^}
+	DEBUG: "$DEBUG"
+	NOW: "$NOW"
+	localtime: "$(date +'%Y/%m/%d %H:%M:%S %z')"
+	isotime: "$(date +'%FT%T%z')"
 	EOF
     # jq_from_text user_data < "$PROJDIR"/scripts/user-data.sh | cfn-flip >> "$PROJDIR"/vars/deploy.yaml
+    J2DEFS+=(-D "PUBLISHING=${PUBLISHING^}" -D "DEBUG=$DEBUG" -D "bootstrapUrl=$bootstrapUrl" -D "region=${AWS_DEFAULT_REGION}")
 
     local -a urls=() quick_urls=()
     test -n "${URL_FILE:-}" && rm -f "${URL_FILE}" || true
-    if [ -n "${MANIFEST:-}" ]; then
-        packer_manifest_all $MANIFEST > $TMPDIR/vars/images.yaml
-    fi
     local ami_id
     if [ -n "${IMAGE_ID:-}" ]; then
         ami_id="$IMAGE_ID"
@@ -519,46 +532,113 @@ dc2_upload() {
             if ! ami_id=$(aws ec2 describe-images --owners self --filters \
                 Name=tag:Version,Values=${VERSION} \
                 Name=tag:BaseOS,Values="*${OSID}*" \
-                Name=name,Values='xdp-*' | aws_format_images | head -1 | awk '{print $2}'); then
+                "Name=name,Values=${PROJECT}*" | aws_format_images | head -1 | awk '{print $2}'); then
                 die "Failed to find valid AMI"
             fi
             debug "Found New AMI: $ami_id"
         fi
     fi
-    aws ec2 describe-images --image-ids $ami_id --query 'Images[].Tags[]' | jq '{ami: map_values({(.Key): .Value})|add}' | cfn-flip > "$TMPDIR"/vars/image.yaml
-    for YAML in "$PROJDIR"/*.{yaml,template}; do
-        if ! test -f "$YAML"; then
-            continue
+    if [ -n "${MANIFEST:-}" ]; then
+        local UUID
+        if [ -n "$IMAGE_ID" ]; then
+            UUID="$(jq -r ".builds[]|select(.artifact_id | contains(\"$IMAGE_ID\"))|.packer_run_uuid" $MANIFEST)"
         fi
-        TEMPLATE=$(basename "${YAML%%.*}")
-        cfn-flip "$YAML" > "${GENDIR}/${TEMPLATE}.json"
+        packer_manifest_all $MANIFEST $UUID > $TMPDIR/vars/images.yaml
+    fi
+    mkdir -p "$GENDIR"/scripts/
+    for ii in "$PROJDIR"/scripts/*; do
+        if [[ $ii =~ .j2$ ]]; then
+            cat "$PROJDIR"/vars/*.yaml "${USER_VARS_FILES[@]}" | jinja2 "${J2DEFS[@]}" "$ii" > $GENDIR/scripts/$(basename $ii .j2)
+        else
+            cp $ii $GENDIR/scripts/
+        fi
     done
-    for J2TEMPLATE in "$PROJDIR"/*.j2; do
-        if ! test -f "$J2TEMPLATE"; then
-            continue
+    if test -e "$PROJDIR"/lambda; then
+        LAMBDASUM=$(cd "$PROJDIR/lambda" && sha256sum $(ls ./*.py requirements.txt 2>/dev/null || true) | tee "$GENDIR/lambda.sha256" | sha256sum - | cut -d' ' -f1 | tee $GENDIR/lambdasum.sha256)
+        LAMBDAKEY="${PREFIX}lambda/${LAMBDASUM:0:2}/${LAMBDASUM:2:2}/${LAMBDASUM}.zip"
+        if aws s3api head-object --bucket ${BUCKET} --key ${LAMBDAKEY} >/dev/null 2>&1; then
+            :
+        else
+            mkdir -p "$GENDIR"/lambda
+            cp "$PROJDIR"/lambda/*.py $GENDIR/lambda/
+            if test -e "$PROJDIR"/lambda/requirements.txt; then
+                cp "$PROJDIR"/lambda/requirements.txt "$GENDIR"/lambda/
+                cd "$GENDIR"
+                #docker run -it --rm -e container=docker -v  $GENDIR:$GENDIR -w /var/task -e PIP_TRUSTED_HOST=10.10.2.136 -e HOME=/var/task -- lambci/lambda:build-${LRUNTIME} /bin/bash -l -x -e -c "mkdir -p lambda; ${LPIP} install -r $GENDIR/lambda/requirements.txt -t lambda/ && cd lambda && zip -9r $GENDIR/lambda.zip ."
+            fi
+            (cd "$GENDIR"/lambda && zip -q -9r $GENDIR/lambda.zip .)
+            rm -rf "$GENDIR"/lambda
+            aws s3 cp --acl public-read lambda.zip s3://${BUCKET}/${LAMBDAKEY}
         fi
-        if [[ $J2TEMPLATE =~ quickcreate ]]; then
-            continue
-        fi
-        TEMPLATE=$(basename $J2TEMPLATE)
-        TEMPLATE="${TEMPLATE%%.*}"
-        for flavor in ${FLAVORS//,/ }; do
-            case "$flavor" in
-                default) TEMPLATEOUT=${TEMPLATE} ;;
-                *) TEMPLATEOUT=${TEMPLATE}-${flavor} ;;
-            esac
-            templateUrl="${BASE_URL}/${TEMPLATEOUT}.json"
-            cat "$PROJDIR"/vars/*.yaml "$TEMPLATEDIR"/flavor/${flavor}.yaml "$TMPDIR"/vars/*.yaml > $TMPDIR/allvars.yaml
+    fi
 
-            local templateJson=${GENDIR}/${TEMPLATEOUT}.json
+    J2DEFS+=(-D ami_id="${ami_id}")
+    J2DEFS+=(-D deploy_email="$(git config user.email || id -un)")
+    J2DEFS+=(-D deploy_host="$(hostname -s)")
+    J2DEFS+=(-D is_automated="${IS_AUTOMATED}")
+    aws ec2 describe-images --image-ids $ami_id --query 'Images[].Tags[]' | jq '{ami: map_values({(.Key): .Value})|add}' | cfn-flip > "$TMPDIR"/vars/image.yaml
+
+    declare -A templatUrlFlavors=()
+    local j2Template templateFile flavor
+    local envYaml="${TEMPLATEDIR}/env/${ENVIRONMENT}.yaml"
+    test -r "$envYaml" || die "$envYaml doesn't exist. You need to specify a valid environment or create an environment file"
+    for j2Template in $(find "$PROJDIR" -name '*.template.j2' -type f); do
+        if ! test -f "$j2Template"; then
+            continue
+        fi
+        templateFile=$(basename $j2Template)
+        templateFile="${templateFile%%.*}"
+        if [[ $templateFile =~ quickcreate ]]; then
+            continue
+        fi
+        for flavor in ${FLAVORS//,/ }; do
+            local flavorYaml="$TEMPLATEDIR"/flavor/${flavor}.yaml
+            if ! test -e "$flavorYaml"; then
+                echo >&2 "*** WARNING: Specified flavor: $flavor is missing $flavorYaml. Skipping. ***"
+                continue
+            fi
+            case "$flavor" in
+                default)
+                    flavor_suffix=''
+                    ;;
+                *)  flavor_suffix="-${flavor}"
+                    ;;
+            esac
+
+            templateOut=${templateFile}${flavor_suffix}
+            templateUrl="${BASE_URL}/${templateOut}.json"
+            local j2Locals=(-D "templateUrl=$templateUrl" -D flavor="$flavor" -D flavor_suffix="$flavor_suffix")
+            local allVars=$TMPDIR/allvars.yaml
+
+
+            cat "$PROJDIR"/vars/*.yaml "$flavorYaml" "$envYaml" "$TMPDIR"/vars/*.yaml | cfn-flip > ${allVars%.yaml}.json
+            cat "$PROJDIR"/vars/*.yaml "$flavorYaml" "$envYaml" "$TMPDIR"/vars/*.yaml > $allVars
+
+            local templateJson=${GENDIR}/${templateOut}.json
             # shellcheck disable=SC2002
             set -o pipefail
-            if ! jinja2 -D "PUBLISHING=${PUBLISHING^}" -D "DEBUG=$DEBUG" -D "bootstrapUrl=$bootstrapUrl" -D "ami_""${AWS_DEFAULT_REGION//-/_}""=$ami_id" -D "region=${AWS_DEFAULT_REGION}" -D "ami_id=$ami_id" -D "templateUrl=$templateUrl" "$J2TEMPLATE" "$TMPDIR"/allvars.yaml \
-                | tee ${TMPDIR}/${TEMPLATEOUT}.yaml \
-                | cfn-flip > "$templateJson"; then
+            if ! jinja2 "${J2DEFS[@]}" "${j2Locals[@]}" "$j2Template" "$allVars" > "${TMPDIR}/${templateOut}.yaml"; then
                 #| jq_put_userata_in_lt $PROJDIR/scripts/user-data.sh > "$templateJson"; then
-                die "Failed to apply jinja template $templateJson"
+                error "***** ERROR ****"
+                error "CmdLine:"
+                error ""
+                error "jinja2 ${J2DEFS[*]} ${j2Locals[*]} $j2Template $allVars"
+                die "Failed to apply Jinja template ${TMPDIR}/${templateOut}.yaml"
             fi
+            if ! cfn-flip "${TMPDIR}/${templateOut}.yaml" > "$templateJson"; then
+                error "***** ERROR ****"
+                error "CmdLine:"
+                error ""
+                die "Failed to convert: cfn-flip ${TMPDIR}/${templateOut}.yaml"
+            fi
+            if [ -s "${INLINE_SCRIPT:-}" ]; then
+                if cfn_replace_userdata "${INLINE_SCRIPT}" < "$templateJson" > "${templateJson}.tmp"; then
+                    mv "${templateJson}.tmp" "$templateJson"
+                else
+                    warn "Failed to inject user-data $INLINE_SCRIPT into $templateJson"
+                fi
+            fi
+
             set +o pipefail
             if test -x $TEMPLATEDIR/verify.sh; then
                 echo >&2 "Running verify script"
@@ -570,18 +650,26 @@ dc2_upload() {
             if ! templateMd5=$(md5sum "${templateJson}" | awk '{print $1}') || [ -z "$templateMd5" ]; then
                 die "Failed to generate md5 for input"
             fi
-            validateS3="s3://${BUCKET}/.tmp/validation/${templateMd5}/${TEMPLATEOUT}.json"
-            if ! s3_cp "${GENDIR}/${TEMPLATEOUT}.json" "$validateS3"; then
+            validateS3="s3://${BUCKET}/.tmp/validation/${templateMd5}/${templateOut}.json"
+            if ! s3_cp "${GENDIR}/${templateOut}.json" "$validateS3"; then
                 die "Failed to upload template for validation to $validateS3"
             fi
-            if ! aws cloudformation validate-template --template-url "$(aws_s3_url "$validateS3")" | tee deployment.json | tee "$TMPDIR/${TEMPLATEOUT}.parameters.json" > /dev/null; then
-                die "Failed to validate ${GENDIR}/${TEMPLATEOUT}.json"
+            echo >&2
+            aws cloudformation validate-template --template-url "$(aws_s3_url "$validateS3")" --region "$AWS_DEFAULT_REGION" | tee "$TMPDIR/${templateOut}.parameters.json" > /dev/null
+            if [ ${PIPESTATUS[0]} -ne 0 ]; then
+                die "Failed to validate ${GENDIR}/${templateOut}.json"
             fi
-            if [ -n "${URL_FILE:-}" ]; then
-                echo "$templateUrl" > "$URL_FILE"
-            fi
+
+
+            local quickUrl
             quickUrl="$(aws_quickcreate "$templateUrl" my-${PROJECT})"
-            quick_urls+=("$quickUrl")
+            if [[ $templateFile =~ ^x[cd]p- ]]; then
+                templatUrlFlavors[${flavor}]="$templateUrl"
+                quickUrls[$flavor]="$quickUrl"
+                if [ -n "${URL_FILE:-}" ]; then
+                    echo "$templateUrl" >> "${URL_FILE}.$$"
+                fi
+            fi
             urls+=("$templateUrl")
 
             if [ "$flavor" != default ]; then
@@ -593,6 +681,7 @@ dc2_upload() {
             fi
         done
     done
+    mv "${URL_FILE}.$$" "${URL_FILE}"
 
     if ((DRY)); then
         s3_sync --dryrun "${GENDIR}/" "s3://${BUCKET}/${TARGET}/" >&2
@@ -605,6 +694,7 @@ dc2_upload() {
         fi
         s3_sync ${GENDIR}/ "s3://${BUCKET}/${TARGET}/" >&2
     fi
+    echo "${templatUrlFlavors[@]}"
 
     #cd - > /dev/null
 }
@@ -631,15 +721,21 @@ dc2_cleanup() {
 
 dc2_defaults() {
     declare -g FIND_AMI=0 DRY=0 KEEP=0 DEBUG=${DEBUG:-0} CLOUD=aws MODE='create'
-    declare -g ENVIRONMENT=dev PUBLISHING=${PUBLISHING:-False}
+    declare -g ENVIRONMENT=${ENVIRONMENT:-dev}
+    declare -r -g PUBLISHING=${PUBLISHING:-false}
     declare -g INSTALLER_RC="${INSTALLER_RC:-''}"
-    declare -g TMPBASE="${TMPDIR:-/tmp}/$(basename $0 .sh)-$(id -u)" # EG /tmp/dc2-1000/
+    declare -r -g TMPBASE="${TMPDIR:-/tmp}/$(basename $0 .sh)-$(id -u)" # EG /tmp/dc2-1000/
+    declare -g LRUNTIME="python3.6"
+    declare -g LPIP="pip3"
+    declare -g PREFIX=''
+    declare -r -g IS_AUTOMATED="${IS_AUTOMATED:-false}"
+
     export DEBUG PUBLISHING
 
     declare -g -a J2DEFS=()
     case "$CLOUD" in
-        aws) declare -g TEMPLATEDIR="$XLRINFRADIR"/aws/cfn ;;
-        azure) declare -g TEMPLATEDIR="$XLRINFRADIR"/azure/arm ;;
+        aws) declare -r -g TEMPLATEDIR="$XLRINFRADIR"/aws/cfn ;;
+        azure) declare -r -g TEMPLATEDIR="$XLRINFRADIR"/azure/arm ;;
         *) die "Unsupported cloud $CLOUD" ;;
     esac
     mkdir -p "$TMPBASE" || die "Failed to create $TMPBASE"
@@ -648,6 +744,9 @@ dc2_defaults() {
 }
 
 dc2_main() {
+    if ! test -z "$VIRTUAL_ENV"; then
+        source "$XLRINFRADIR"/.venv/bin/activate
+    fi
     dc2_defaults
     [ $# -eq 0 ] && set -- --help
 
