ENG-8020 dcc: XCE container management fixes
- Many small fixes to dcc tool from user feedback
- Integrate ytt to help with duplication [YAML sprawl](https://get-ytt.io/)
- Fixes for Packer image building

Change-Id: I16f0a90b5da70b70132026c3d842172fc455f8fb

diff --git a/bin/dcc b/bin/dcc
--- a/bin/dcc
+++ b/bin/dcc
@@ -10,7 +10,7 @@
 #   5/5/2020: Moved here from xcalar.git repo
 #
 # shellcheck disable=SC2206,SC2207,SC2164,SC2155
-# shellcheck disable=SC2154,SC2028,SC2029
+# shellcheck disable=SC2154,SC2028,SC2029,SC1091
 
 set -e
 
@@ -56,6 +56,15 @@ EOF
 }
 
 DC=${DC:-$(basename $0)}
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+export XLRINFRADIR="$(cd "$DIR"/.. && pwd)"
+export PATH=$XLRINFRADIR/bin:$PATH
+
+. infra-sh-lib
+if ((DEBUG)); then
+    set -xv
+    traceon
+fi
 
 say() {
     printf "%s\n" "$1" >&2
@@ -126,6 +135,9 @@ enter [node-id or name]
 
 load FILE
     Load image from FILE (usually a .tar.gz or tar.bz2).
+
+doctor
+    Fix common issues. Note this will stop/delete your cluster.
 
 tour
     A quick overview of features/commands offered by $DC
@@ -278,6 +290,30 @@ set_cluster_config() {
     set_config "${CLUSTER}.${var}" "$@"
 }
 
+
+mkec2env() {
+    cat <<-EOF
+	AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}
+	CLUSTER_NAME=${CLUSTER}
+	CLUSTERSIZE=${NODES}
+	BUCKET=${BUCKET:-xcfield}
+	WORKBUCKET=${WORKBUCKET:-sharedinf-workbucket-559166403383-us-west-2}
+	EVENTPREFIX=${EVENPREFIX:-.events/}
+	WORKPREFIX=${CLUSTER_UUID}/
+	NFSHOST=${CLUSTER}-0
+	NFSIP=${SUBNET%.0}.2
+	SUBNET=${NETWORK}
+	SSLKEYFILE=/etc/xcalar/localhost.key
+	SSLCRTFILE=/etc/xcalar/localhost.crt
+    HOSTEDZONENAME=$(dnsdomainname)
+    CNAME=${CLUSTER_UUID}.$(dnsdomainname)
+	KINESISROLEARN=${KINESISROLEARN:-arn:aws:iam::559166403383:role/abakshi-instamart-KinesisServiceRole-K6TURBTVX2EF}
+	BASEURL=${BASEURL:-}
+	LOGBUCKET=${LOGBUCKET:-sharedinf-workbucket-559166403383-us-west-2}
+	LOGPREFIX=/logs/559166403383/${CLUSTER_UUID}/
+	EOF
+}
+
 mkconfig() {
     local cluster="${1:-xcalar}"
     local xnodes="${2:-1}" node_id xnodes_1
@@ -288,6 +324,10 @@ mkconfig() {
         cat <<- EOF
 		// Generated by dcc
 		Constants.XcalarRootCompletePath=/mnt/xcalar
+		Constants.XcalarLogCompletePath=/var/log/xcalar
+		Constants.XdbLocalSerDesPath=/ephemeral/data/serdes
+		Constants.XdbSerDesMode=2
+		Constants.XdbSerDesMaxDiskMB=2000
 		Constants.BufferCacheLazyMemLocking=true
 		Constants.SendSupportBundle=false
 		Constants.Cgroups=false
@@ -320,8 +360,29 @@ mkenv() {
             value="${!key}"
         fi
         envlist+=("$key=$value")
-        echo "${key}='${value}'"
+        echo "${key}=${value}"
     done
+}
+
+mks3config() {
+    cat <<EOF
+    {
+     "s3buckets":{
+        "S3Bucket":{
+            "bucket":"${BUCKET}",
+            "prefix":"",
+            "event_prefix":"",
+            "existing":true
+        },
+        "WorkBucket":{
+            "bucket":"${WORKBUCKET}",
+            "prefix":"${WORKPREFIX:-}",
+            "event_prefix":"${EVENTPREFIX:-.events/}",
+            "existing":false
+        }
+      }
+    }
+EOF
 }
 
 # Returns $1*system-memory
@@ -332,6 +393,24 @@ pct_memory() {
 
 volume_time() {
     date -d "$(docker volume inspect ${1:-$SHARE} -f '{{.CreatedAt}}')" +%s 2>/dev/null
+}
+
+check_bridge() {
+    local subnet="$1" br
+    for br in $(ip addr show type bridge | awk -F: '/^[0-9]/{print $2}' | grep -v docker0); do
+        if ip addr show dev $br | grep -Eq "brd ${subnet%.0.0}.0.255"; then
+            warn "Deleting brdige network $br"
+            (set -x; sudo ip link delete $br type bridge)
+        fi
+    done
+}
+
+cmd_doctor() {
+    parse_args "$@"
+    cmd_rm -f "$@"
+    check_brdige "$SUBNET"
+    docker volume ls -q --filter=label=cluster=$CLUSTER | xargs -r docker volume rm
+    docker network rm ${NETWORK}
 }
 
 dc2_defaults() {
@@ -351,19 +430,24 @@ dc2_defaults() {
         -v /sys/fs/cgroup:/sys/fs/cgroup:ro
         -v /var/run/docker.sock:/var/run/docker.sock
     )
-    DEFAULT_PATH=/opt/xcalar/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+    DEFAULT_PATH=/opt/xcalar/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/xcalar/lib/java8/jre/bin
     REGISTRY=${REGISTRY:-registry.int.xcalar.com}
     REPO=${REPO:-xcalar/xcalar}
     CLUSTER=${CLUSTER:-xcalar}
     NETWORK="${NETWORK:-$(get_cluster_config network ${CLUSTER}net)}"
     SUBNET="${SUBNET:-$(get_cluster_config subnet 172.20.0.0)}"
-    CIDR_BITS="${CIDR_BITS:-$(get_cluster_config cidr 24)}"
+    CIDR_BITS="${CIDR_BITS:-$(get_cluster_config cidr 16)}"
     NODES="${NODES:-$(get_cluster_config nodes 3)}"
     SHARE="${SHARE:-$(get_cluster_config share ${CLUSTER}_root)}"
+    SERDES="${SERDES:-$(get_cluster_config serdes ${CLUSTER}_serdes)}"
     IMAGE_ID="${IMAGE_ID:-$(get_cluster_config image registry.int.xcalar.com/xcalar/xcalar:latest)}"
     HOSTPORT="${HOSTPORT:-$(get_cluster_config hostport 18443)}"
     NODE_ID=${NODE_ID:-0}
-    STACK_NAME="${STACK_NAME:-''}"
+    STACK_NAME="${STACK_NAME:-$CLUSTER}"
+    if ! test -e "$CONFDIR/${CLUSTER}-uuid.txt"; then
+        uuidgen > "$CONFDIR/${CLUSTER}-uuid.txt"
+    fi
+    CLUSTER_UUID=${CLUSTER}-$(cat "$CONFDIR/${CLUSTER}-uuid.txt")
 }
 
 parse_args() {
@@ -377,6 +461,9 @@ parse_args() {
             -h | --help)
                 cmd_help "$@"
                 exit 0
+                ;;
+            --pull)
+                PULL=1
                 ;;
             -n | --nodes)
                 NODES=$1
@@ -470,6 +557,7 @@ parse_args() {
             else
                 IMAGE_ID="${IMAGE_TAG}"
             fi
+            PULL=1
         fi
     fi
     dc2_defaults
@@ -535,31 +623,35 @@ cmd_stop() {
 
     #docker ps -a | grep ${CLUSTER}- | awk '{print $1}' | xargs -r docker stop
     local names name
-    names=($(docker ps -a --filter label="cluster=$CLUSTER" --format '{{.Names}}'))
-    if [ $? -eq 0 ] && [ "${#names[@]}" -gt 0 ]; then
-        local -a stop=()
-        for name in "${names[@]}"; do
-            local sts
-            if sts="$(docker container inspect $name --format '{{.State.Status}}')"; then
-                case "$sts" in
-                    created | paused | exited)
-                        echo "! Skipping $node as it is in $sts state"
-                        ;;
-                    running)
-                        stop+=($name)
-                        ;;
-                    *) echo "! Skipping $name. Unknown state: $sts" ;;
-                esac
-            fi
-        done
-        if [ "${#stop[@]}" -gt 0 ]; then
-            say "- Stopping ${stop[*]} ..."
-            docker stop "${stop[@]}"
-        else
-            say "- All members already stopped"
-        fi
-    else
+    if ! names=($(docker ps -a --filter label="cluster=$CLUSTER" --format '{{.Names}}')); then
         say "- Cluster $CLUSTER has no members"
+        return 0
+    fi
+    if [ "${#names[@]}" -eq 0 ]; then
+        say "- Cluster $CLUSTER has no members"
+        return 0
+    fi
+
+    local -a stop=()
+    for name in "${names[@]}"; do
+        local sts
+        if sts="$(docker container inspect $name --format '{{.State.Status}}')"; then
+            case "$sts" in
+                created | paused | exited)
+                    echo "! Skipping $node as it is in $sts state"
+                    ;;
+                running)
+                    stop+=($name)
+                    ;;
+                *) echo "! Skipping $name. Unknown state: $sts" ;;
+            esac
+        fi
+    done
+    if [ "${#stop[@]}" -gt 0 ]; then
+        say "- Stopping ${stop[*]} ..."
+        docker stop "${stop[@]}"
+    else
+        say "- All members already stopped"
     fi
 }
 
@@ -619,6 +711,49 @@ cmd_logs() {
     return 0
 }
 
+preflight_check() {
+    if ((PULL)) || ! docker image inspect "$IMAGE_ID" > /dev/null 2>&1 || [[ $IMAGE_ID =~ :latest$ ]]; then
+        if ! docker pull $IMAGE_ID; then
+            die "Failed to pull $IMAGE_ID"
+        fi
+    fi
+    if docker volume inspect "$SHARE" >/dev/null 2>&1; then
+        if ! docker run --rm --entrypoint=/bin/bash -u xcalar -v $SHARE:/mnt/xcalar -- $IMAGE_ID -c 'test -w /mnt/xcalar' >/dev/null; then
+            error "Permissions on $SHARE are not allowing xcalar to write to it. Please remove $SHARE"
+            say ""
+            say "       docker volume rm $SHARE"
+            say "       docker volume rm $SERDES"
+            say ""
+            die "Bad permissions on xcalar shared root volume"
+        fi
+    else
+        if ! docker volume create --label cluster=$CLUSTER --label purpose=xcalar_shared_root $SHARE >/dev/null; then
+            die "Failed to create volume $SHARE"
+        fi
+    fi
+    if ! docker volume inspect "$SERDES" >/dev/null 2>&1; then
+        if ! docker volume create --label cluster=$CLUSTER --label purpose=xcalar_serdes $SERDES >/dev/null; then
+            die "Failed to create volume $SERDES"
+        fi
+    fi
+    # One time setup per cluster
+    if ! docker network inspect "$NETWORK" > /dev/null 2>&1; then
+        if ! docker network create --attachable --label cluster=$CLUSTER --subnet "${SUBNET}/${CIDR_BITS}" --gateway ${SUBNET%.0}.1 -d bridge "${NETWORK}"; then
+            die "Unable to create network $NETWORK (${SUBNET}/${CIDR_BITS})"
+        fi
+    fi
+    if ! SUBNET_CIDR=$(docker network inspect $NETWORK --format '{{json .}}' | jq -r '.IPAM.Config[0].Subnet'); then
+        die "Unable to query network $NETWORK (${SUBNET}/${CIDR_BITS})"
+    fi
+
+    CIDR_BITS_NEW="${SUBNET_CIDR#*/}"
+    SUBNET_NEW="${SUBNET_CIDR%/*}"
+    if [ "$CIDR_BITS_NEW" != "$CIDR_BITS" ] || [ "$SUBNET" != "$SUBNET_NEW" ]; then
+        error "Your desired subnet of $SUBNET/$CIDR_BITS doesn't match what $NETWORK is configured for ($SUBNET_CIDR)"
+        die "Please fix your configuration, or run '$DC doctor'"
+    fi
+}
+
 cmd_run() {
     parse_args "$@"
 
@@ -632,37 +767,11 @@ cmd_run() {
     local defaultEnv="${CONFDIR}/${CLUSTER}.default.env"
     local tmpFsPctOfPhysicalMem=$(get_cluster_config shm_pct 70)
     local tmpFsSizeKb=$(pct_memory $tmpFsPctOfPhysicalMem)
-
-    if ! docker image inspect "$IMAGE_ID" > /dev/null 2>&1 || [[ $IMAGE_ID =~ :latest$ ]]; then
-        if ! docker pull $IMAGE_ID; then
-            die "Failed to pull $IMAGE_ID"
-        fi
-    fi
-    if docker volume inspect "$SHARE" >/dev/null 2>&1; then
-        if ! docker run --rm --entrypoint=/bin/bash -u xcalar -v $SHARE:/mnt/xcalar $IMAGE_ID -c 'test -w /mnt/xcalar' >/dev/null; then
-            say "ERROR: Permissions on $SHARE are not allowing xcalar to write to it. Please remove $SHARE"
-            say ""
-            say "       docker volume rm $SHARE"
-            say ""
-            die "Bad permissions on xcalar shared root volume"
-        fi
-    else
-        if ! docker volume create --label cluster=$CLUSTER --label purpose=xcalar_shared_root $SHARE >/dev/null; then
-            die "Failed to create volume $SHARE"
-        fi
-    fi
-    # One time setup per cluster
-    if ! docker network inspect "$NETWORK" > /dev/null 2>&1; then
-        if ! docker network create --attachable --label cluster=$CLUSTER --subnet "${SUBNET}/${CIDR_BITS}" --gateway ${SUBNET%.0}.1 -d bridge "${NETWORK}"; then
-            die "Unable to create network $NETWORK (${SUBNET}/${CIDR_BITS})"
-        fi
-    fi
-    if ! SUBNET_CIDR=$(docker network inspect $NETWORK --format '{{json .}}' | jq -r '.IPAM.Config[0].Subnet'); then
-        die "Unable to query network $NETWORK (${SUBNET}/${CIDR_BITS})"
+    if ! test -e $XLRGUIDIR/xcalar-gui/s3buckets.json; then
+        mks3config > $XLRGUIDIR/xcalar-gui/s3buckets.json
     fi
 
-    CIDR_BITS="${SUBNET_CIDR#*/}"
-    SUBNET="${SUBNET_CIDR%/*}"
+    preflight_check
 
     say "+ Creating ${NODES} node cluster from image ${IMAGE_ID} ..."
 
@@ -688,15 +797,18 @@ cmd_run() {
     fi
 
     DC_ARGS=(
+        -v ${XLRINFRADIR}/packer/docker/docker-entrypoint.sh:/docker-entrypoint.sh:ro
         -v ${SHARE}:/mnt/xcalar
+        -v ${SERDES}:/ephemeral/data
         --memory-swappiness=10
         --shm-size=${tmpFsSizeKb%.*}k
         --network $NETWORK
         -e CLUSTER=$CLUSTER
         -e XCE_NUMNODES=$NODES
         -e PATH=$DEFAULT_PATH
-        -e XCE_CONFIG=/etc/xcalar/default.cfg)
-    ENVS+=(CLUSTER=$CLUSTER XCE_NUMNODES=$NODES PATH=$DEFAULT_PATH XCE_CONFIG=/etc/xcalar/default.cfg)
+    )
+
+    ENVS+=(CLUSTER=$CLUSTER XCE_NUMNODES=$NODES PATH=$DEFAULT_PATH)
     if [ -n "${VOLUMES:-}" ]; then
         local vol
         for vol in "${VOLUMES[@]}"; do
@@ -704,17 +816,14 @@ cmd_run() {
         done
     fi
     if ((LOCALDEPLOY)); then
-        DC_ARGS+=(
-            -e XLRDIR=/opt/xcalar
-            -e JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
-            -e PATH=$XLRDIR/bin:$DEFAULT_PATH
-            -e XCE_CONFIG=/etc/xcalar/default.cfg
-        )
-        ENVS+=(XLRDIR=/opt/xcalar PATH=$XLRDIR/bin:$DEFAULT_PATH XCE_CONFIG=/etc/xcalar/default.cfg JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk)
         REMAP_PROGS=($XLRDIR/bin/usrnode $XLRDIR/bin/childnode $XLRDIR/bin/xcmgmtd $XLRDIR/bin/xcmonitor)
         for prog in "${REMAP_PROGS[@]}"; do
             local link
-            link=$(readlink -f $prog)
+            if ! link=$(readlink -f $prog); then
+                say "ERROR: Failed to readlink $prog!"
+                return 1
+            fi
+
             if ! test -e $link; then
                 say "ERROR: $prog doesn't exist"
                 return 1
@@ -856,6 +965,8 @@ cmd_clean() {
     fi
     say " - Shared volume $SHARE"
     docker volume rm $SHARE 2> /dev/null || true
+    say " - SerDes volume $SHARE"
+    docker volume rm $SERDES 2> /dev/null || true
     return 0
 }
 
@@ -877,7 +988,7 @@ init() {
     AWS_PASSTHROUGH=0
     SSHKEY=${SSHKEY:-$CONFDIR/ssh/id_xctest}
     SSHCFG=${SSHCFG:-$CONFDIR/ssh/config}
-    mkdir -m 0700 -p $(dirname $SSHKEY)
+    mkdir -p $(dirname $SSHKEY)
     chmod 0700 $(dirname $SSHKEY)
     touch $SSHCFG
     chmod 0600 $SSHCFG
@@ -921,5 +1032,5 @@ main() {
 ALLCMDS=($(grep -Eow '^cmd_([a-z]+)' "${BASH_SOURCE[0]}" | sed 's/^cmd_//' | sort))
 main "$@"
 exit $?
-#__SCRIPT__ENDS__
+__SCRIPT__ENDS__
 __PAYLOAD__STARTS__
