ENG-8154 - dcc modifications for dev/test
Changes here support dev and test work with dcc

- /etc/default/xcalar is made rw to allow runtime modification
- python libs are copied into the /op/xcalar/lib/python3.6/site-packages in --local
mode to keep them compatible with childnode binaries
- cluster_exec command is implemented to allow a single dcc command to modify all nodes

This change requires: https://gerrit.int.xcalar.com/c/xcalar/+/21406

Change-Id: I394f0ee5dc13835740f62a85530814179707d6a7

diff --git a/bin/dcc b/bin/dcc
--- a/bin/dcc
+++ b/bin/dcc
@@ -10,7 +10,7 @@
 #   5/5/2020: Moved here from xcalar.git repo
 #
 # shellcheck disable=SC2206,SC2207,SC2164,SC2155,SC2086
-# shellcheck disable=SC2154,SC2028,SC2029,SC1091
+# shellcheck disable=SC2154,SC2028,SC2029,SC1091,SC1090
 # shellcheck disable=SC2036,SC2034
 
 set +e
@@ -872,7 +872,7 @@ dcc_cmd_run() {
         HTTPS_PORT_MAP="${HOSTPORT}:443"
     fi
 
-    ENVS+=(CLUSTER XCE_NUMNODES=$NODES XCE_USE_GUARDRAILS)
+    ENVS+=(CLUSTER "XCE_NUMNODES=${NODES}" XCE_USE_GUARDRAILS)
     if [ -n "${VOLUMES:-}" ]; then
         local vol
         for vol in "${VOLUMES[@]}"; do
@@ -898,22 +898,24 @@ dcc_cmd_run() {
         DC_ARGS+=(-v ${XLRGUIDIR}/xcalar-gui:/opt/xcalar/xcalar-gui)
         DC_ARGS+=(-v ${XLRDIR}:${XLRDIR})
         DC_ARGS+=(-v ${XLRDIR}/scripts:/opt/xcalar/scripts)
-        DC_ARGS+=(--label localdeploy="$XLRDIR")
-        ENVS+=(XLRDIR XLRDIROVL=$XLRDIR VIRTUAL_ENV=$XLRDIR/xcve PATH=$XLRDIR/xcve/bin:$XLRDIR/bin:$DEFAULT_PATH)
+        DC_ARGS+=(--label "localdeploy=$XLRDIR")
+        ENVS+=(XLRDIR "XLRDIROVL=${XLRDIR}" "VIRTUAL_ENV=${XLRDIR}/xcve" "PATH=${XLRDIR}/xcve/bin:${XLRDIR}/bin:${DEFAULT_PATH}")
+        ENVS+=(PYTHONPATH="$XLRDIR"/cmake_binary_dir/src/bin/sdk/core:"$XLRDIR"/src/bin/sdk/xpu:"$XLRDIR"/src/bin/sdk/controller:"$XLRDIR"/src/bin/sdk/xdp:"$XLRDIR"/src/bin/util:"$XLRDIR"/src/bin/xc2)
+
     else
-        ENVS+=(XLRDIR=/opt/xcalar PATH=$DEFAULT_PATH)
+        ENVS+=("XLRDIR=/opt/xcalar" "PATH=${DEFAULT_PATH}")
     fi
 
     ENVS+=(ENV_FILE)
     DC_ARGS+=(-v $CONFDIR:$CONFDIR)
 
     LABELS=(
-        --label image-id="${IMAGE_ID}"
-        --label nodes=${NODES}
-        --label cluster=${CLUSTER}
-        --label owner=dcc
+        --label "image-id=${IMAGE_ID}"
+        --label "nodes=${NODES}"
+        --label "cluster=${CLUSTER}"
+        --label "owner=dcc"
     )
-    DC_ARGS+=(-v $ENV_FILE:/etc/default/xcalar:ro)
+    DC_ARGS+=(-v $ENV_FILE:/etc/default/xcalar:rw)
     DC_ARGS+=(-v $DEFAULTCFG:/etc/xcalar/default.cfg)
     DC_ARGS+=(--env-file $ENV_FILE)
     if [ -n "$MAXMEM" ]; then
@@ -928,8 +930,8 @@ dcc_cmd_run() {
         fi
         # map entire CONFDIR into container and add meminfo path to MEMINFO env variable
         mv ${MEMINFO}.tmp ${MEMINFO}
-        ENVS+=(CLUSTER_SAME_PHYSICAL_NODE=true)
-        ENVS+=(MEMINFO=${MEMINFO})
+        ENVS+=("CLUSTER_SAME_PHYSICAL_NODE=true")
+        ENVS+=(MEMINFO)
         info "Meminfo file ($MEMINFO) has been created for this cluster."
     fi
     if [ -n "$NUMCPU" ]; then
@@ -944,7 +946,7 @@ dcc_cmd_run() {
     for node_id in $(seq 0 $((NODES - 1))); do
         name=${CLUSTER}-${node_id}
         ip_address=$(docker_container_mkip $node_id)
-        local NODE_ARGS=(--name ${name} --hostname ${name} --ip $ip_address -e XCE_NODEID=$node_id --label node-id=$node_id -p 22)
+        local NODE_ARGS=(--name ${name} --hostname ${name} --ip $ip_address -e "XCE_NODEID=${node_id}" --label "node-id=${node_id}" -p 22)
         if [ $node_id -eq 0 ]; then
             NODE_ARGS+=(-p $HTTPS_PORT_MAP -P)
         fi
@@ -1028,6 +1030,47 @@ dcc_cmd_shell() {
     local node
     node=$(docker_cluster_node $NODE_ID)
     docker exec -it ${CUSER:+-u $CUSER} ${WORKDIR:+-w $WORKDIR} $node /bin/bash -l
+}
+
+dcc_cmd_cluster_exec() {
+    parse_args "$@"
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            --)
+                shift
+                break
+                ;;
+        esac
+        shift
+    done
+
+    local names name pid rc
+    local -a pids
+    local -i anyfailed=0 n=0
+    if ! names=($(docker ps -a --filter label="cluster=$CLUSTER" --format '{{.Names}}')); then
+        say "- Cluster $CLUSTER has no members"
+        return 0
+    fi
+    if [ "${#names[@]}" -eq 0 ]; then
+        say "- Cluster $CLUSTER has no members"
+        return 0
+    fi
+
+    for name in "${names[@]}"; do
+        docker exec ${CUSER:+-u $CUSER} ${WORKDIR:+-w $WORKDIR} $name "$@" &
+        pids+=($!)
+    done
+    for pid in "${pids[@]}"; do
+        wait "$pid"
+        rc=$?
+        if [ "$rc" != "0" ]; then
+            echo "Error running command \"$*\" on node ${names[n]}"
+            anyfailed=1
+        fi
+        n=$(( n + 1 ))
+    done
+
+    return $anyfailed
 }
 
 dcc_cmd_ssh() {
@@ -1141,12 +1184,12 @@ init() {
 
 dcc_defaults() {
     SYSTEMD_ARGS=(
-        --security-opt seccomp=unconfined
-        --ulimit core=-1:-1
-        --ulimit nofile=120000:120000
-        --ulimit nproc=140960:140960
-        --ulimit memlock=-1:-1
-        --ulimit stack=-1:-1
+        --security-opt "seccomp=unconfined"
+        --ulimit "core=-1:-1"
+        --ulimit "nofile=120000:120000"
+        --ulimit "nproc=140960:140960"
+        --ulimit "memlock=-1:-1"
+        --ulimit "stack=-1:-1"
         --cap-add CAP_SYS_PTRACE
         --cap-add CAP_IPC_LOCK
         --tmpfs /run
@@ -1441,7 +1484,7 @@ if [ "$(basename -- "${BASH_SOURCE[0]}")" = "$(basename -- "$0")" ]; then
     fi
 
     DC="${DC:-$(basename "$0")}"
-    ALLCMDS=($(grep -Eow '^dcc_cmd_([a-z]+)' "${BASH_SOURCE[0]}" | sed 's/^dcc_cmd_//' | sort))
+    ALLCMDS=($(grep -Eow '^dcc_cmd_([a-z_]+)' "${BASH_SOURCE[0]}" | sed 's/^dcc_cmd_//' | sort))
     dcc_main "$@"
     exit $?
 fi
