ENG-8765 - Creating meminfo file in dcc launch script
If "--maxswap" and "--maxmem" params are provided, we use this to
populate the meminfo file. If not, then the appropriate memory and swap
values are set to (current_value / num_nodes).

This meminfo file is then mapped into the containerized cluster, and
the usrnodes are notified to use the provided meminfo file through
the MEMINFO and CLUSTER_SAME_PHYSICAL_NODE env variables.

**Note, there are some stylistic changes as a result of running
shfmt_w.sh.

Change-Id: Ia4276dec3417a4ffb88fedc3d4ebdf9ed7350ed2

diff --git a/bin/dcc b/bin/dcc
--- a/bin/dcc
+++ b/bin/dcc
@@ -15,7 +15,7 @@
 set -e
 
 banner() {
-    cat << 'EOF'
+    cat <<'EOF'
 
                   ____    ____     ____
                  /\  _`\ /\  _`\  /\  _`\
@@ -82,7 +82,7 @@ cmd_help() {
     printf '%s ' "${ALLCMDS[*]}"
     echo
 
-    cat << EOF | sed -n '/^'${1:-.}'/,/^$/p' | sed 's/^/\t/'
+    cat <<EOF | sed -n '/^'${1:-.}'/,/^$/p' | sed 's/^/\t/'
 
 run [-t|--tag TAG]
     [--aws]
@@ -146,7 +146,7 @@ EOF
 }
 
 cmd_tour() {
-    cat << EOF
+    cat <<EOF
 
     Quickstart a 3 node cluster on your local machine of build 2.3.0 RC3
 
@@ -217,8 +217,8 @@ docker_container_mkip() {
 docker_container_ip() {
     local node_id="${1:-0}" node
     local cluster="${2:-$CLUSTER}"
-    if node=$(docker ps --filter "label=cluster=$cluster" --filter "label=node-id=$node_id" --format '{{.ID}}' 2> /dev/null); then
-        docker container inspect $node --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 2> /dev/null
+    if node=$(docker ps --filter "label=cluster=$cluster" --filter "label=node-id=$node_id" --format '{{.ID}}' 2>/dev/null); then
+        docker container inspect $node --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 2>/dev/null
     fi
 }
 
@@ -250,7 +250,7 @@ docker_cluster_node() {
     local node_id="$1" cluster="${2:-$CLUSTER}"
 
     local -a nodes
-    if ! nodes=($(docker ps --filter "label=cluster=$cluster" ${node_id:+--filter "label=node-id=$node_id"} --format '{{.Names}}' 2> /dev/null)); then
+    if ! nodes=($(docker ps --filter "label=cluster=$cluster" ${node_id:+--filter "label=node-id=$node_id"} --format '{{.Names}}' 2>/dev/null)); then
         say "Failed to get container for cluster=${cluster} node-id=$node_id"
         return 2
     fi
@@ -262,7 +262,7 @@ docker_cluster_node() {
 
 get_config() {
     local val
-    if val="$(git config -f "$CONFIG" --get "$1" 2> /dev/null)"; then
+    if val="$(git config -f "$CONFIG" --get "$1" 2>/dev/null)"; then
         echo "$val"
         return 0
     elif [ -n "${2:-}" ]; then
@@ -327,7 +327,7 @@ mkconfig() {
     if [ -e "${TEMPLATE:-}" ]; then
         cat "$TEMPLATE"
     else
-        cat <<- EOF
+        cat <<-EOF
 		// Generated by dcc
 		Constants.XcalarRootCompletePath=/mnt/xcalar
 		Constants.XcalarLogCompletePath=/var/log/xcalar
@@ -405,7 +405,10 @@ check_bridge() {
     for br in $(ip addr show type bridge | awk -F: '/^[0-9]/{print $2}' | grep -v docker0); do
         if ip addr show dev $br | grep -Eq "brd ${subnet%.0.0}.0.255"; then
             warn "Deleting brdige network $br"
-            (set -x; sudo ip link delete $br type bridge)
+            (
+                set -x
+                sudo ip link delete $br type bridge
+            )
         fi
     done
 }
@@ -449,7 +452,7 @@ dc2_defaults() {
     NODE_ID=${NODE_ID:-0}
     STACK_NAME="${STACK_NAME:-$CLUSTER}"
     if ! test -e "$CONFDIR/${CLUSTER}-uuid.txt"; then
-        uuidgen > "$CONFDIR/${CLUSTER}-uuid.txt"
+        uuidgen >"$CONFDIR/${CLUSTER}-uuid.txt"
     fi
     CLUSTER_UUID=${CLUSTER}-$(cat "$CONFDIR/${CLUSTER}-uuid.txt")
 }
@@ -459,8 +462,8 @@ parse_args() {
         local cmd="$1"
         shift
         case "$cmd" in
-            xcalar-[0-9]) NODE_ID="${cmd#xcalar-}";;
-            $CLUSTER-[0-9]) NODE_ID="${cmd#${CLUSTER}-}";;
+            xcalar-[0-9]) NODE_ID="${cmd#xcalar-}" ;;
+            $CLUSTER-[0-9]) NODE_ID="${cmd#${CLUSTER}-}" ;;
             [0-9]) NODE_ID="$cmd" ;;
             -h | --help)
                 cmd_help "$@"
@@ -468,6 +471,10 @@ parse_args() {
                 ;;
             --maxmem)
                 MAXMEM="$1"
+                shift
+                ;;
+            --maxswap)
+                MAXSWAP="$1"
                 shift
                 ;;
             --numcpu)
@@ -580,7 +587,7 @@ cmd_tags() {
     say "Tags for ${REGISTRY}/${REPO}:"
     say ""
     local tags ii
-    if tags="$(reg tags "${REGISTRY}/${REPO}" 2> /dev/null)"; then
+    if tags="$(reg tags "${REGISTRY}/${REPO}" 2>/dev/null)"; then
         for ii in $tags; do
             echo -e "\t${ii}"
         done
@@ -598,7 +605,7 @@ cmd_ls() {
     parse_args "$@"
 
     local tags tag
-    if tags=($(reg ls --skip-ping $REGISTRY 2> /dev/null | grep "^${REPO} " | tr ',' ' ' | tr ' ' '\n' | sed '/^$/d')); then
+    if tags=($(reg ls --skip-ping $REGISTRY 2>/dev/null | grep "^${REPO} " | tr ',' ' ' | tr ' ' '\n' | sed '/^$/d')); then
         echo -e "Remote tags in $REGISTRY:\n"
         repo="${tags[0]}"
         tags=("${tags[@]:1}")
@@ -706,7 +713,7 @@ cmd_rm() {
     names=($(docker container ls -a --filter label=cluster=${CLUSTER} --format '{{.Names}}'))
     if [ "${#ids[@]}" -gt 0 ]; then
         say "- Removing ${names[*]}"
-        docker rm -v ${FORCE} "${names[@]}" > /dev/null
+        docker rm -v ${FORCE} "${names[@]}" >/dev/null
     else
         say "- Cluster $CLUSTER has no members"
     fi
@@ -733,7 +740,7 @@ docker_volume_version() {
 
 #shellcheck disable=SC2181
 preflight_check() {
-    if ((PULL)) || ! docker image inspect "$IMAGE_ID" > /dev/null 2>&1 || [[ $IMAGE_ID =~ :latest$ ]]; then
+    if ((PULL)) || ! docker image inspect "$IMAGE_ID" >/dev/null 2>&1 || [[ $IMAGE_ID =~ :latest$ ]]; then
         if ! docker pull $IMAGE_ID; then
             die "Failed to pull $IMAGE_ID"
         fi
@@ -765,7 +772,7 @@ preflight_check() {
         fi
     fi
     # One time setup per cluster
-    if ! docker network inspect "$NETWORK" > /dev/null 2>&1; then
+    if ! docker network inspect "$NETWORK" >/dev/null 2>&1; then
         if ! docker network create --attachable --label cluster=$CLUSTER --subnet "${SUBNET}/${CIDR_BITS}" --gateway ${SUBNET%.0}.1 -d bridge "${NETWORK}"; then
             die "Unable to create network $NETWORK (${SUBNET}/${CIDR_BITS}), try $DC doctor"
         fi
@@ -782,6 +789,44 @@ preflight_check() {
     fi
 }
 
+# If "--maxswap" and "--maxmem" params are provided, we use this to
+# populate the meminfo file. If not, then the appropriate memory and swap
+# values are set to (current_value / num_nodes).
+mkmeminfo() {
+    emit() {
+        printf '%-18s %d kB\n' "${1}:" "$2"
+    }
+    if [ -z "$MAXMEM" ]; then
+        MEMTOTAL=$(grep MemTotal /proc/meminfo | awk '{print $2}')
+        MEMFREE=$(grep MemFree /proc/meminfo | awk '{print $2}')
+        MEMTOTAL=$((MEMTOTAL / NODES))
+        MEMFREE=$((MEMFREE / NODES))
+    else
+        MEMTOTAL=$MAXMEM
+        MEMFREE=$MAXMEM
+    fi
+    if [ -z "$MAXSWAP" ]; then
+        SWAPTOTAL=$(grep SwapTotal /proc/meminfo | awk '{print $2}')
+        SWAPFREE=$(grep SwapFree /proc/meminfo | awk '{print $2}')
+        SWAPTOTAL=$((SWAPTOTAL / NODES))
+        SWAPFREE=$((SWAPFREE / NODES))
+    else
+        SWAPTOTAL=$MAXSWAP
+        SWAPFREE=$MAXSWAP
+    fi
+
+    # All values in kb.
+    emit MemTotal "$MEMTOTAL"
+    emit MemFree "$MEMFREE"
+    emit Cached 0
+    emit SwapCached 0
+    emit Buffers 0
+    emit Shmem "$((MEMTOTAL * 70 / 100))"
+    emit SwapTotal "$SWAPTOTAL"
+    emit SwapFree "$SWAPFREE"
+    emit SReclaimable 0
+}
+
 cmd_run() {
     parse_args "$@"
 
@@ -796,7 +841,7 @@ cmd_run() {
     local tmpFsPctOfPhysicalMem=$(get_cluster_config shm_pct 70)
     local tmpFsSizeKb=$(pct_memory $tmpFsPctOfPhysicalMem)
     if ! test -e $XLRGUIDIR/xcalar-gui/s3buckets.json; then
-        mks3config > $XLRGUIDIR/xcalar-gui/s3buckets.json
+        mks3config >$XLRGUIDIR/xcalar-gui/s3buckets.json
     fi
 
     preflight_check
@@ -805,15 +850,13 @@ cmd_run() {
 
     AWS_SUPPORT=()
     ENVS=()
-    if [ -n "$MAXMEM" ]; then
-        ENVS+=(MAXMEM=$MAXMEM)
-    fi
     if [ -n "$NUMCPU" ]; then
         ENVS+=(NUMCPU=$NUMCPU)
     fi
     ENVS+=(CLUSTER_SAME_PHYSICAL_NODE="true")
+
     if ((AWS_PASSTHROUGH)); then
-        if vault-aws-credentials-provider.sh --ttl 12h -e 2> /dev/null | sed 's/^ //; /export /d' > $CONFDIR/aws.env.tmp; then
+        if vault-aws-credentials-provider.sh --ttl 12h -e 2>/dev/null | sed 's/^ //; /export /d' >$CONFDIR/aws.env.tmp; then
             mv $CONFDIR/aws.env{.tmp,}
         fi
         if test -e "$CONFDIR/aws.env"; then
@@ -870,13 +913,27 @@ cmd_run() {
         DC_ARGS+=(--label localdeploy="$XLRDIR")
         DC_ARGS+=(-e XLRDIR -e XLRGUIDIR)
     fi
+
+    MEMINFO=$CONFDIR/meminfo
+    if mkmeminfo >"${MEMINFO}.tmp"; then
+        mv "${MEMINFO}.tmp" "${MEMINFO}"
+    else
+        error "Generating meminfo file: ${MEMINFO}.tmp"
+        cat ${MEMINFO}.tmp >&2
+        die "/proc/meminfo replacement"
+    fi
+    # map entire CONFDIR into container and add meminfo path to MEMINFO env variable
+    DC_ARGS+=(-v $CONFDIR:$CONFDIR)
+    ENVS+=(MEMINFO=${MEMINFO})
+    echo "Meminfo file ($MEMINFO) has been created for this cluster."
+
     LABELS=(
         --label image-id="${IMAGE_ID}"
         --label nodes=${NODES}
         --label cluster=${CLUSTER}
     )
-    mkenv "${ENVS[@]}" > $defaultEnv
-    mkconfig $CLUSTER $NODES > $defaultCfg
+    mkenv "${ENVS[@]}" >$defaultEnv
+    mkconfig $CLUSTER $NODES >$defaultCfg
     DC_ARGS+=(-v $defaultEnv:/etc/default/xcalar:ro)
     DC_ARGS+=(-v $defaultCfg:/etc/xcalar/default.cfg)
     DC_ARGS+=(--env-file $defaultEnv)
@@ -898,21 +955,21 @@ cmd_run() {
     done
 
     printf '%s\n' " + Starting ${#cids[@]} containers ..." >&2
-    docker start "${cids[@]}" > /dev/null
+    docker start "${cids[@]}" >/dev/null
     local site sqldf
     site="$(docker port ${cids[0]} 443 2>/dev/null | sed 's@0.0.0.0@https://'${HOST:-$(hostname -f)}'@g')"
     sqldf="$(docker port ${cids[0]} 10000 2>/dev/null | sed 's@0.0.0.0@'${HOST:-$(hostname -f)}'@g')"
     if [ -n "$site" ]; then echo "XD: $site"; else echo "WARNING: No port for XD exposed on node0!"; fi
     if [ -n "$sqldf" ]; then echo "SQL: $sqldf"; else echo "WARNING: No port for SqlDf on node0!"; fi
-    : > $SSHCFG
+    : >$SSHCFG
     chmod 0600 $SSHCFG
     for node_id in $(seq 0 $((NODES - 1))); do
         name=${CLUSTER}-${node_id}
         ip_address="$(docker_container_mkip $node_id)"
         local ssh_port=22
-        printf 'Host %s node%d\n\tHostname %s\n\tPort %s\n\n' $name $node_id $ip_address $ssh_port >> $SSHCFG
+        printf 'Host %s node%d\n\tHostname %s\n\tPort %s\n\n' $name $node_id $ip_address $ssh_port >>$SSHCFG
     done
-    cat >> $SSHCFG << EOF
+    cat >>$SSHCFG <<EOF
 
 Host *
     StrictHostKeyChecking   no
@@ -940,7 +997,7 @@ cmd_load() {
         elif [[ $file =~ .tar.gz$ ]]; then
             pigz -dc "$file" | docker load || die "Failed to load $file"
         elif [[ $file =~ .tar$ ]]; then
-            docker load < "$file" || die "Failed to load $file"
+            docker load <"$file" || die "Failed to load $file"
         else
             die "Don't know how to load $file. Use docker load."
         fi
@@ -1001,7 +1058,7 @@ cmd_clean() {
         docker rm -v -f $members
     fi
     say " - Shared volume $SHARE"
-    docker volume rm -f $SHARE 2> /dev/null || true
+    docker volume rm -f $SHARE 2>/dev/null || true
     return 0
 }
 
@@ -1039,7 +1096,7 @@ main() {
     start_time=$(date +%s)
     init
     test $# -gt 0 || set -- help
-    if grep -q -- "$1" <<< "${ALLCMDS[@]}"; then
+    if grep -q -- "$1" <<<"${ALLCMDS[@]}"; then
         CMD="$1"
         shift
         if ! cmd_${CMD} "$@"; then
