ovirttool docker wrapper: ensure ub14 Docker image build locally
Change-Id: I147dbb1d19b689ee8fdb82a93ca30c54dd727f6c

diff --git a/bin/ovirttool b/bin/ovirttool
--- a/bin/ovirttool
+++ b/bin/ovirttool
@@ -8,6 +8,12 @@ if [ -z "$XLRINFRADIR" ]; then
 fi
 cd $XLRINFRADIR
 
+if ! docker image inspect ub14-build >/dev/null 2>&1; then
+    echo >&2 "Hey you need to build ub14-build container before you can run this script! Read the setup section of the ovirttool wiki http://wiki.int.xcalar.com/mediawiki/index.php/Ovirttool#Setup, or I can try to do it for you"
+    cd $XLRDIR/docker/ub14 && make && echo "Done! Run me again" || echo "Failed to run docker make :("
+    exit 1
+fi
+
 if ! docker image inspect ovirttool >/dev/null 2>&1; then
     TMP="$(mktemp -d -t ovirtool.XXXXXX)"
     docker build -t ovirttool -f "$XLRINFRADIR/docker/ovirttool.df" "$TMP"
