AMP: Default to Standard_D14_v2_Promo in applianceMainTemplate
- Apply the changes from azuredeploy.json to applianceMainTemplate
- Add make target 'deployMain' to test applianceMainTemplate directly
- Remove defaults from parameters.json so we can share it between azuredeploy
  and applianceMainTemplate

Change-Id: Ifede56f1be601d733c31b704cf577179d8710944

diff --git a/azure/xdp-standard/Makefile b/azure/xdp-standard/Makefile
--- a/azure/xdp-standard/Makefile
+++ b/azure/xdp-standard/Makefile
@@ -7,6 +7,11 @@ BOOTSTRAP = ../bootstrap/ampBootstrap.sh
 S3_INSTALLER_URL = s3://xcrepo/builds/bc8beef7-0649eba1/prod/xcalar-1.2.1-1088-installer
 S3_BOOTSTRAP_URL = s3://xcrepo/bysha1/$(shell sha1sum $(BOOTSTRAP) | awk '{print $$1}')/$(shell basename $(BOOTSTRAP))
 
+SCRIPTS_URI=$(shell jq -r .variables.scriptsUri applianceMainTemplate.json | sed -e 's@^http://@@g')
+SCRIPTS_NAME=$(shell jq -r .variables.customScriptName applianceMainTemplate.json)
+SCRIPTS_PATH=$(SCRIPTS_URI)/$(SCRIPTS_NAME)
+SCRIPTS_SHA1=$(shell sha1sum $(BOOTSTRAP) | cut -d' ' -f1)
+
 all: xdp-standard-package.zip
 
 xdp-standard-package.zip: createUiDefinition.json applianceMainTemplate.json mainTemplate.json
@@ -25,6 +30,24 @@ group:
 delete:
 	az group delete --name $(GROUP) --no-wait
 
+check_bootstrap:
+	@http_proxy=; \
+     if ! test "`curl -sSL http://$(SCRIPTS_PATH) | sha1sum | cut -d' ' -f1`" = "$(SCRIPTS_SHA1)"; then \
+        echo >&2 "ERROR: Checksum of $(BOOTSTRAP) doesn't match with what's referenced in your applianceMainTemplate (http://$(SCRIPTS_PATH))"; \
+        exit 1; \
+     fi
+
+update_bootstrap:
+	@http_proxy=; \
+    if test "`curl -o /dev/null -w '%{http_code}' -sSL http://$(SCRIPTS_PATH) 2>/dev/null`" != 200; then \
+        gsutil cp $(BOOTSTRAP) gs://$(SCRIPTS_PATH); \
+    elif test "`curl -sSL http://$(SCRIPTS_PATH) 2>/dev/null | sha1sum | cut -d' ' -f1`" = "$(SCRIPTS_SHA1)"; then \
+        echo >&2 "http://$(SCRIPTS_PATH) already up-to-date"; \
+    else \
+        echo >&2 "http://$(SCRIPTS_PATH) already exists with a different checksum! Not overwriting! Bump the version in applianceMainTemplate.json."; \
+        exit 1; \
+    fi
+
 %.json: %.json.example
 	@test -e $@ || { cp -v $< $@; @echo "Please modify the password in parameters.json before!"; exit 1; }
 	@touch $@
@@ -35,12 +58,16 @@ deploy: group parameters.json
     BOOTSTRAP_URL=`aws s3 presign --expires-in 3600 $(S3_BOOTSTRAP_URL)` && \
     echo $${INSTALLER_URL} && \
     echo $${BOOTSTRAP_URL} && \
-    time az group deployment create --resource-group $(GROUP) --name mydeploy \
+    time az group deployment create --resource-group $(GROUP) --name $(GROUP)-deploy \
      --template-file azuredeploy.json \
      --parameters @parameters.json \
      --parameters "{\"installerUrl\": { \"value\": \"$${INSTALLER_URL}\"}}" \
-     --parameters "{\"bootstrapUrl\": { \"value\": \"$${BOOTSTRAP_URL}\"}}" \
-     --parameters "{\"licenseKey\": { \"value\": \"`cat /etc/xcalar/XcalarLic.key`\"}}"
+     --parameters "{\"bootstrapUrl\": { \"value\": \"$${BOOTSTRAP_URL}\"}}"
+
+deployMain: check_bootstrap group parameters.json
+	time az group deployment create --resource-group $(GROUP) --name $(GROUP)-deploy \
+     --template-file applianceMainTemplate.json \
+     --parameters @parameters.json
 
 getips:
 	@az vm list-ip-addresses --resource-group $(GROUP) --output json --query '[].virtualMachine.network.publicIpAddresses[].[name,ipAddress]' --output tsv
