Azure: Add "dataDiskSize" to parameters
- Add template validation preflight check
- Template validation was failing due to missing 'kind' param on SA
- Instead of encoding defaults into local user value for all of
time, put them into a defaults file and merge:
- Ensure that you have jq1.5
- Disallow multiple deploys into the same RG
- Show https:// URL at end of deploy

Change-Id: I3fe3c9afa87b7ccf58e78b02ca0d361b239d5edd

diff --git a/azure/xdp-standard/Makefile b/azure/xdp-standard/Makefile
--- a/azure/xdp-standard/Makefile
+++ b/azure/xdp-standard/Makefile
@@ -1,33 +1,41 @@
 .PHONY: all clean deploy group deploy
 
 SHELL = /bin/bash
-GROUP = $(shell id -un)-rg
-LOCATION  = westus2
-BOOTSTRAP = ../bootstrap/ampBootstrap.sh
 NOW = $(shell date +'%Y%m%d%H%M')
 
-BUCKET = xcrepo
-S3_INSTALLER = s3://$(BUCKET)/builds/e5c22263-01d66bb7/prod/xcalar-1.2.2-1191-installer
-S3_BOOTSTRAP_KEY = bysha1/$(shell sha1sum $(BOOTSTRAP) | awk '{print $$1}')/$(shell basename $(BOOTSTRAP))
-S3_BOOTSTRAP = s3://$(BUCKET)/$(S3_BOOTSTRAP_KEY)
-ZONE = azure.xcalar.io
-PARAMETERS = parameters.json
+GROUP ?= $(shell id -un)-rg
+LOCATION  ?= westus2
+DEPLOY = $(GROUP)-deploy
+VALIDATE_RG = validate-$(LOCATION)-rg
 
-COUNT=$(shell jq -r '.parameters.scaleNumber.value' $(PARAMETERS))
-EMAIL=$(shell jq -r '.parameters.adminEmail.value' $(PARAMETERS))
+
+BOOTSTRAP ?= ../bootstrap/ampBootstrap.sh
+BUCKET ?= xcrepo
+S3_INSTALLER ?= s3://$(BUCKET)/builds/e5c22263-01d66bb7/prod/xcalar-1.2.2-1191-installer
+S3_BOOTSTRAP ?= s3://$(BUCKET)/bysha1/$(shell sha1sum $(BOOTSTRAP) | awk '{print $$1}')/$(shell basename $(BOOTSTRAP))
+S3_BOOTSTRAP_KEY = $(subst s3://$(BUCKET)/,,$(S3_BOOTSTRAP))
+ZONE ?= azure.xcalar.io
+PARAMETERS ?= parameters.json
+PARAMETERS_DEFAULTS ?= parameters.json.defaults
+TEMPLATE ?= azuredeploy.json
+
+
 PASSWORD=$(shell jq -r '.parameters.adminPassword.value' $(PARAMETERS))
 USERNAME=$(shell jq -r '.parameters.adminUsername.value' $(PARAMETERS))
-LICENSE=$(shell jq -r '.parameters.licenseKey.value' $(PARAMETERS))
 
 SCRIPTS_PATH=$(shell jq -r '[.variables.scriptsUri,.variables.customScriptName]|join("/")' applianceMainTemplate.json | sed -e 's@^http://@@g')
 SCRIPTS_SHA1=$(shell sha1sum $(BOOTSTRAP) | cut -d' ' -f1)
 
 export GNUPGHOME=$(CURDIR)/.gnupg
-TEMPLATE=azuredeploy.json
+JQ=/usr/local/bin/jq
 
 s3url = $(shell aws s3 presign --expires-in 3600 $(1))
 
 -include local.mk
+
+# These are the full URLs, possibly with parameter eg: https://xcrepo.s3.amazonaws.com/builds/foo.sh?Arg-1&Arg2=2
+BOOTSTRAP_URL := $(call s3url, $(S3_BOOTSTRAP))
+INSTALLER_URL := $(call s3url, $(S3_INSTALLER))
 
 all: xdp-standard-package.zip
 
@@ -35,8 +43,13 @@ all: xdp-standard-package.zip
 	@echo "You need sshpass installed. Please use 'sudo apt-get install -y sshpass' on Ubuntu and 'sudo yum install -y sshpass' on EL"
 	exit 1
 
+jq15:
+	@if ! jq --version | grep -q '1.5'; then sudo curl -o $(JQ).tmp -fsSL https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && sudo chmod +x $(JQ).tmp && sudo mv $(JQ).tmp $(JQ); fi
+	@hash -r; jq --version | grep -q '1.5' || { echo "jq 1.5 had to be installed. Please run 'hash -r', and make sure jq is $(JQ) in your PATH"; exit 2; }
+
 xdp-standard-package.zip: createUiDefinition.json applianceMainTemplate.json mainTemplate.json
-	aws s3 cp $(BOOTSTRAP) - >/dev/null 2>&1 || { aws s3 cp $(BOOTSTRAP) $(S3_BOOTSTRAP) && aws s3api put-object-acl --acl public-read --bucket $(BUCKET) --key $(S3_BOOTSTRAP_KEY); }
+	aws s3 cp $(S3_BOOTSTRAP) - >/dev/null 2>&1 || aws s3 cp $(BOOTSTRAP) $(S3_BOOTSTRAP)
+	aws s3api put-object-acl --acl public-read --bucket $(BUCKET) --key $(S3_BOOTSTRAP_KEY)
 	sed -i -e 's|"scriptsUri":.*$$|"scriptsUri": "https://'$(BUCKET)'.s3.amazonaws.com/'`dirname $(S3_BOOTSTRAP_KEY)`'",|g' applianceMainTemplate.json
 	cp createUiDefinition.json applianceCreateUiDefinition.json
 	zip xdp-standard-package.zip applianceCreateUiDefinition.json createUiDefinition.json applianceMainTemplate.json mainTemplate.json
@@ -45,9 +58,9 @@ clean:
 	rm -f xdp-standard-package.zip applianceCreateUiDefinition.json
 	rm -rf .tmp/
 
-group:
-	@if ! test "`az group exists --name $(GROUP) --output tsv`" = true; then \
-        az group create --name $(GROUP) --location $(LOCATION); \
+$(VALIDATE_RG) $(GROUP):
+	@if ! test "`az group exists --name $@ --output tsv`" = true; then \
+        az group create --name $@ --location $(LOCATION); \
     fi
 
 destroy:
@@ -73,50 +86,58 @@ update_bootstrap:
     fi
 
 %.json: %.json.example
-	@test -e $@ || { cp -v $< $@; @echo "Please modify the password in $(PARAMETERS) before!"; exit 1; }
+	@test -e $@ || { echo "Copying template $< to $@ ..." && cp $< $@ && echo "Please modify the missing sections in $(PARAMETERS) before redeploying!"; exit 1; }
 	@touch $@
 
-validate_params: $(PARAMETERS)
-	@echo "$(EMAIL)" | grep -q '@xcalar.com' || { echo "Need to specify email!"; exit 1; }
-	@test "$(COUNT)" -ge 1 || { echo "Need to specify valid scaleNumber!"; exit 1; }
-	@test "$$(echo $(LICENSE) | wc -c)" -ge 40 || { echo "Need to specify valid scaleNumber!"; exit 1; }
 
-
-deploy: validate_params group
+validate: $(VALIDATE_RG) parameters.json
 	@bash -n $(BOOTSTRAP)
-	@aws s3 cp $(BOOTSTRAP) - >/dev/null 2>&1 || aws s3 cp $(BOOTSTRAP) $(S3_BOOTSTRAP)
-	@(touch local.mk; cat local.mk; echo GROUP=$(GROUP)) | uniq | tee local.mk.tmp >/dev/null && mv local.mk.tmp local.mk
-	time az group deployment create --resource-group $(GROUP) --name $(GROUP)-deploy-$(NOW) \
+	@aws s3 cp $(S3_BOOTSTRAP) - >/dev/null 2>&1 || aws s3 cp $(BOOTSTRAP) $(S3_BOOTSTRAP)
+	@az group deployment validate --resource-group $(VALIDATE_RG) \
      --template-file "$(TEMPLATE)" \
-     --parameters "$$(jq -r '.parameters | {\
-                                           adminEmail, adminUsername, adminPassword, licenseKey, scaleNumber,\
+     --parameters "$$(jq -r -s '.[0] * .[1] | .parameters | {\
+                                           adminEmail, adminUsername, adminPassword, licenseKey, scaleNumber, dataDiskSize,\
                                            dnsLabelPrefix: {value:"$(GROUP)"},\
                                            installerUrl: {value:"$(call s3url,$(S3_INSTALLER))"},\
                                            bootstrapUrl: {value:"$(call s3url,$(S3_BOOTSTRAP))"}\
-                                           }|tojson' $(PARAMETERS))"
+                                           }|tojson' $(PARAMETERS_DEFAULTS) $(PARAMETERS))" --output json
 
-deployDev: validate_params group
+deploy: $(GROUP) validate
+	@(touch local.mk; cat local.mk; echo GROUP=$(GROUP)) | uniq | tee local.mk.tmp >/dev/null && mv local.mk.tmp local.mk
+	time az group deployment create --resource-group $(GROUP) --name $(DEPLOY) \
+     --template-file "$(TEMPLATE)" \
+     --parameters "$$(jq -r -s '.[0] * .[1] | .parameters | {\
+                                           adminEmail, adminUsername, adminPassword, licenseKey, scaleNumber, dataDiskSize,\
+                                           dnsLabelPrefix: {value:"$(GROUP)"},\
+                                           installerUrl: {value:"$(call s3url,$(S3_INSTALLER))"},\
+                                           bootstrapUrl: {value:"$(call s3url,$(S3_BOOTSTRAP))"}\
+                                           }|tojson' $(PARAMETERS_DEFAULTS) $(PARAMETERS))"
+	@echo "Your cluster is available at https://$$(az group deployment show --resource-group $(GROUP) --name $(DEPLOY) --output json --query 'properties.outputs.url.value' --output tsv)"
+
+deployDev: $(GROUP) validate
 	bash -n $(BOOTSTRAP)
-	aws s3 cp $(BOOTSTRAP) - >/dev/null 2>&1 || { aws s3 cp $(BOOTSTRAP) $(S3_BOOTSTRAP) && aws s3api put-object-acl --acl public-read --bucket $(BUCKET) --key $(S3_BOOTSTRAP_KEY); }
+	aws s3 cp $(S3_BOOTSTRAP) - >/dev/null 2>&1 || { aws s3 cp $(BOOTSTRAP) $(S3_BOOTSTRAP) && aws s3api put-object-acl --acl public-read --bucket $(BUCKET) --key $(S3_BOOTSTRAP_KEY); }
 	sed -i -e 's|"scriptsUri":.*$$|"scriptsUri": "https://'$(BUCKET)'.s3.amazonaws.com/'`dirname $(S3_BOOTSTRAP_KEY)`'",|g' applianceDevTemplate.json
 	@(touch local.mk; cat local.mk; echo GROUP=$(GROUP)) | uniq | tee local.mk.tmp >/dev/null && mv local.mk.tmp local.mk
-	time az group deployment create --resource-group $(GROUP) --name $(GROUP)-deploy-$(NOW) \
+	time az group deployment create --resource-group $(GROUP) --name $(DEPLOY) \
      --template-file applianceDevTemplate.json \
-     --parameters "$$(jq -r '.parameters | {\
-                                           adminEmail, adminUsername, adminPassword, licenseKey, scaleNumber,\
+     --parameters "$$(jq -r -s '.[0] * .[1] | .parameters | {\
+                                           adminEmail, adminUsername, adminPassword, licenseKey, scaleNumber, dataDiskSize,\
                                            dnsLabelPrefix: {value:"$(GROUP)"},\
                                            installerUrl: {value:"$(call s3url,$(S3_INSTALLER))"},\
                                            bootstrapUrl: {value:"$(call s3url,$(S3_BOOTSTRAP))"}\
-                                           }|tojson' $(PARAMETERS))"
+                                           }|tojson' $(PARAMETERS_DEFAULTS) $(PARAMETERS)"
+	@echo "Your cluster is available at https://$$(az group deployment show --resource-group $(GROUP) --name $(DEPLOY) --output json --query 'properties.outputs.url.value' --output tsv)"
 
-deployMain: validate_params group
+deployMain: $(GROUP) validate_main
 	bash -n $(BOOTSTRAP)
-	aws s3 cp $(BOOTSTRAP) - >/dev/null 2>&1 || { aws s3 cp $(BOOTSTRAP) $(S3_BOOTSTRAP) && aws s3api put-object-acl --acl public-read --bucket $(BUCKET) --key $(S3_BOOTSTRAP_KEY); }
+	aws s3 cp $(S3_BOOTSTRAP) - >/dev/null 2>&1 || { aws s3 cp $(BOOTSTRAP) $(S3_BOOTSTRAP) && aws s3api put-object-acl --acl public-read --bucket $(BUCKET) --key $(S3_BOOTSTRAP_KEY); }
 	sed -i -e 's|"scriptsUri":.*$$|"scriptsUri": "https://'$(BUCKET)'.s3.amazonaws.com/'`dirname $(S3_BOOTSTRAP_KEY)`'",|g' applianceMainTemplate.json
 	@(touch local.mk; cat local.mk; echo GROUP=$(GROUP)) | uniq | tee local.mk.tmp >/dev/null && mv local.mk.tmp local.mk
-	time az group deployment create --resource-group $(GROUP) --name $(GROUP)-deploy-$(NOW) \
+	time az group deployment create --resource-group $(GROUP) --name $(DEPLOY) \
      --template-file applianceMainTemplate.json \
      --parameters "$$(jq -r '.parameters | {adminEmail, adminUsername, adminPassword, licenseKey, scaleNumber}|tojson' $(PARAMETERS))"
+	@echo "Your cluster is available at https://$$(az group deployment show --resource-group $(GROUP) --name $(DEPLOY) --output json --query 'properties.outputs.url.value' --output tsv)"
 
 getips:
 	@az vm list-ip-addresses --resource-group $(GROUP) --output json --query '[].virtualMachine.network.publicIpAddresses[].[name,ipAddress]' --output tsv
